### ISSUE TITLE
schema.s.hooks.createWrapperSync is not a function

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [codepunkt/mongoose-patch-history#18]
So, I had an error first, which was 
````Error: First param to `schema.plugin()` must be a function, got "object"````

Adding `.default` like: `const patchHistory = require('mongoose-patch-history').default;` did the trick for me.

Now, I am getting that error, and I am not sure how to handle it.

```
TypeError: schema.s.hooks.createWrapperSync is not a function                                                                      
    at applyHooks (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose\lib\services\model\applyHooks.js:50:5)  
    at Function.compile (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose\lib\model.js:3782:3)              
    at Mongoose.model (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose\lib\index.js:381:22)                
    at createPatchModel (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose-patch-history\lib\index.js:284:27)
    at exports.default (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose-patch-history\lib\index.js:73:17)  
    at Schema.plugin (E:\Info\localhost\Web Development\NodeJS\autotash\node_modules\mongoose\lib\schema.js:1129:3)                
    at Object.<anonymous> (E:\Info\localhost\Web Development\NodeJS\autotash\modules\requests\requests.model.js:55:15)             
    at Module._compile (module.js:635:30)                                                                                          
    at Object.Module._extensions..js (module.js:646:10)                                                                            
    at Module.load (module.js:554:32)                                                                                              
    at tryModuleLoad (module.js:497:12)                                                                                            
    at Function.Module._load (module.js:489:3)                                                                                     
    at Module.require (module.js:579:17)                                                                                           
    at require (internal/module.js:11:18)                                                                                          
    at Object.<anonymous> (E:\Info\localhost\Web Development\NodeJS\autotash\initilize\globalFuns.js:25:33)                        
    at Module._compile (module.js:635:30)                                                                                          
    at Object.Module._extensions..js (module.js:646:10)                                                                            
    at Module.load (module.js:554:32)                                                                                              
    at tryModuleLoad (module.js:497:12)                                                                                            
    at Function.Module._load (module.js:489:3)                                                                                     
    at Module.require (module.js:579:17)                                                                                           
    at require (internal/module.js:11:18)                                                                                          
```

**Comment by KyloJorgensen** [comment]
getting the same issue. I think that it might have something to do with the version I am using the lasted version of mongoose 5

**Comment by AbdelrahmanHafez** [comment]
May be, I am using mongosoe v5 as well

**Comment by codepunkt** [comment]
I'm not sure what the exact problem is.
Can anyone of you provide a complete, minimal and reproducible example as a repository?

**Comment by codepunkt** [comment]
@AbdelrahmanHafez Can you confirm that it works with the latest `mongoose-patch-history` version?

**Comment by AbdelrahmanHafez** [comment]
Yep, the error is gone.

Perhaps add to the documentation the `default` bit in
```
const patchHistory = require('mongoose-patch-history').default;
```

to save people the confusion
