### ISSUE TITLE
Cannot read property '$__' of undefined

### ISSUE THREAD

**Issue by jtlindsey** [codepunkt/mongoose-patch-history#36]
Hello,

Thanks for making this module. It looks like exactly what I was looking for but I'm having trouble getting it to work. I'm trying to add it to a existing model in a app that has no problems without the module. The app does not have a babel dependency so i'm using `require` instead of `import`. Can anyone point out what I'm missing? 

Here is example model:
```
const patchHistory = require('mongoose-patch-history').default;
const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const Purchase = new Schema(
  {
    company: { type: String, trim: true, default: '' },
    refFile: [{ type: Schema.Types.ObjectId, ref: 'File' }],
    status: {
      type: String,
      enum: ['New', 'Old'],
      default: 'New',
    },
    updatedBy: { type: Schema.Types.ObjectId, ref: 'User' },
  },
  {
    timestamps:
      true,
  },
);

Purchase.plugin(patchHistory, { 
  mongoose, 
  name: 'purchasePatches',
  includes: {
    company: { type: String, required: true }
  },
});

module.exports = mongoose.model('Purchase', Purchase);
```

My error when saving new record
```
file error TypeError: Cannot read property '$__' of undefined
    at cleanModifiedSubpaths (/home/test/test_api/node_modules/mongoose-patch-history/node_modules/mongoose/lib/helpers/document/cleanModifiedSubpaths.js:12:46)
    at Array._registerAtomic (/home/test/test_api/node_modules/mongoose-patch-history/node_modules/mongoose/lib/types/array.js:182:7)
    at model.Document.$__set (/home/test/test_api/node_modules/mongoose/lib/document.js:894:11)
    at model.$set (/home/test/test_api/node_modules/mongoose/lib/document.js:780:10)
    at model._handleIndex (/home/test/test_api/node_modules/mongoose/lib/document.js:596:14)
    at model.$set (/home/test/test_api/node_modules/mongoose/lib/document.js:556:24)
    at model.Document (/home/test/test_api/node_modules/mongoose/lib/document.js:85:12)
    at model.Model (/home/test/test_api/node_modules/mongoose/lib/model.js:56:12)
    at new model (/home/test/test_api/node_modules/mongoose/lib/model.js:3939:13)
    at /home/test/test_api/node_modules/mongoose/lib/model.js:2080:22
    at /home/test/test_api/node_modules/async/internal/parallel.js:31:39
    at eachOfArrayLike (/home/test/test_api/node_modules/async/eachOf.js:65:9)
    at exports.default (/home/test/test_api/node_modules/async/eachOf.js:9:5)
    at _parallel (/home/test/test_api/node_modules/async/internal/parallel.js:30:5)
    at parallelLimit (/home/test/test_api/node_modules/async/parallel.js:88:26)
    at /home/test/test_api/node_modules/mongoose/lib/model.js:2096:5
    at new Promise (<anonymous>)
    at Function.create (/home/test/test_api/node_modules/mongoose/lib/model.js:2051:17)
    at createPatch (/home/test/test_api/node_modules/mongoose-patch-history/lib/index.js:138:29)
    at model.<anonymous> (/home/test/test_api/node_modules/mongoose-patch-history/lib/index.js:142:5)
    at _next (/home/test/test_api/node_modules/hooks-fixed/hooks.js:63:32)
    at fnWrapper (/home/test/test_api/node_modules/hooks-fixed/hooks.js:190:8)

```

My error on edit (using `findByIdAndUpdate`)
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '$__' of undefined
    at cleanModifiedSubpaths (/home/test/test_api/node_modules/mongoose-patch-history/node_modules/mongoose/lib/helpers/document/cleanModifiedSubpaths.js:12:46)
    at Array._registerAtomic (/home/test/test_api/node_modules/mongoose-patch-history/node_modules/mongoose/lib/types/array.js:182:7)
    at model.Document.$__set (/home/test/test_api/node_modules/mongoose/lib/document.js:894:11)
    at model.$set (/home/test/test_api/node_modules/mongoose/lib/document.js:780:10)
    at model._handleIndex (/home/test/test_api/node_modules/mongoose/lib/document.js:596:14)
    at model.$set (/home/test/test_api/node_modules/mongoose/lib/document.js:556:24)
    at model.Document (/home/test/test_api/node_modules/mongoose/lib/document.js:85:12)
    at model.Model (/home/test/test_api/node_modules/mongoose/lib/model.js:56:12)
    at new model (/home/test/test_api/node_modules/mongoose/lib/model.js:3939:13)
    at /home/test/test_api/node_modules/mongoose/lib/model.js:2080:22
    at /home/test/test_api/node_modules/async/internal/parallel.js:31:39
    at eachOfArrayLike (/home/test/test_api/node_modules/async/eachOf.js:65:9)
    at exports.default (/home/test/test_api/node_modules/async/eachOf.js:9:5)
    at _parallel (/home/test/test_api/node_modules/async/internal/parallel.js:30:5)
    at parallelLimit (/home/test/test_api/node_modules/async/parallel.js:88:26)
    at /home/test/test_api/node_modules/mongoose/lib/model.js:2096:5
    at new Promise (<anonymous>)
    at Function.create (/home/test/test_api/node_modules/mongoose/lib/model.js:2051:17)
    at createPatch (/home/test/test_api/node_modules/mongoose-patch-history/lib/index.js:138:29)
    at /home/test/test_api/node_modules/mongoose-patch-history/lib/index.js:192:14
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Stack:**   
```
// Node 11.12.0   
// npm 6.7.0   
// MongoDB 3.4.16   

$ npm list mongoose
├── mongoose@4.13.17 
└─┬ mongoose-patch-history@1.3.0
  └── mongoose@5.4.19
```

**Comment by jtlindsey** [comment]
Updated `mongoose` to latest and that revealed a issue in my user model that doesn't affect anything (or show up) unless I'm using 'mongoose-patch-history'. Fixed that issue and `mongoose-patch-history` started working as expected.
