### ISSUE TITLE
Breaking change in new released version v1.4.0: MongoError: unknown top level operator: $push

### ISSUE THREAD

**Issue by BMartinos** [codepunkt/mongoose-patch-history#65]
Hi Team

Thanks for the new release of this module.

I have however picked an issue which has caused a breaking change to occur. It seems that the $push operation is no longer supported with the new changes introduced. Within your test script you have a test which should verify this but it doesnt seem to be working in a real world scenario.

I have created a basic gist of the files and steps needed to reproduce the error. I have made use of your actual test file in the master branch and removed the unrelated sections for this issue (Only testing the **$push** related operation). 
https://gist.github.com/BMartinos/d24dab6cb6d5b77600a5aeb990c0d40f

The error being returned when executing the reproducible test script can be seen below:
```
Error:  { MongoError: unknown top level operator: $push
    at MessageStream.messageHandler (/../mongoose-patch-history-test/node_modules/mongodb/lib/cmap/connection.js:266:20)
    at MessageStream.emit (events.js:198:13)
    at processIncomingData (/../mongoose-patch-history-test/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/../mongoose-patch-history-test/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at MessageStream.Writable.write (_stream_writable.js:299:11)
    at Socket.ondata (_stream_readable.js:710:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) ok: 0, code: 2, codeName: 'BadValue', name: 'MongoError' }
```

**Comment by codepunkt** [comment]
Hey @BMartinos, thanks for the report!

Would you mind trying to install from master via `npm i codepunkt/mongoose-patch-history` or `yarn add codepunkt/mongoose-patch-history` and telling us whether this is fixed there or not?

**Comment by BMartinos** [comment]
@codepunkt great thanks! Pulling from your master branch resolved my issue. Any idea of when this might be published to npm?

**Comment by vinerich** [comment]
I'd say as soon as I figured #63 out to work as I want it too 😅
I'm actively working on getting it resolved so hopefully this week.

**Comment by BMartinos** [comment]
Ok great thanks for the quick feedback @vinerich Will keep an eye out for when the new version is released. Thanks

**Comment by vinerich** [comment]
@BMartinos done 👌🏾 
`2.0.0` was released by @codepunkt and includes the fixes for `$pull, $push` + new [excludes](https://github.com/codepunkt/mongoose-patch-history#excludes) and [rollback without save](https://github.com/codepunkt/mongoose-patch-history#rollback-without-saving) option!

**Comment by BMartinos** [comment]
@vinerich @codepunkt Awesome! thanks for the new release and quick response :). I can confirm this fix is now also in the newly released npm update and working again for me.
